/**
 * DO NOT MODIFY THIS FILE
 */
import "mocha";
import {expect} from "chai";

import {degreesAway} from "../src/degreesAway.js";
import {LinkedMovie} from "../src/responses.js";
import {listActors} from "../src/listActors.js";
import {loadHistory} from "../src/loadHistory.js";

describe("loadHistory", () => {
  it("handles depth 1", async () => {
    await load(1, 78);
  });

  it("handles depth 2", async () => {
    await load(2, 258);
  });

  it("handles depth 3", async () => {
    await load(3, 312);
  });
});

describe("listActors", () => {
  it("handles depth 1", async () => {
    await load(1, 78);

    const response = await listActors({});
    const actors = response.actors;
    expect(actors).length(78);
    let i = 0;
    expect(actors[i++]).to.equal("Adaline Swanson");
    expect(actors[i++]).to.equal("Alessandra Rosenfeld");
    expect(actors[i++]).to.equal("Alex Barber");
    expect(actors[i++]).to.equal("Alex Wolff");
    expect(actors[i++]).to.equal("Alexandra Shipp");
    expect(actors[i++]).to.equal("Alyana Hill");
    expect(actors[i++]).to.equal("Amanda Seyfried");
    expect(actors[i++]).to.equal("Americo Presciutti");
    expect(actors[i++]).to.equal("Andrew Polk");
    expect(actors[i++]).to.equal("Anna Chlumsky");
    expect(actors[i++]).to.equal("Anna Lore");
    expect(actors[i++]).to.equal("Arden Myrin");
    expect(actors[i++]).to.equal("Austin Crute");
    expect(actors[i++]).to.equal("Avery Tiiu Essex");
    expect(actors[i++]).to.equal("Becky Bass");
    expect(actors[i++]).to.equal("Boone Platt");
    expect(actors[i++]).to.equal("Brooke Jaye Taylor");
    expect(actors[i++]).to.equal("Carrie Preston");
    expect(actors[i++]).to.equal("Casie Baker");
    expect(actors[i++]).to.equal("Chris Jackson");
    expect(actors[i++]).to.equal("Christopher R Swanson");
    expect(actors[i++]).to.equal("Colin Blumenau");
    expect(actors[i++]).to.equal("Colson Baker");
    expect(actors[i++]).to.equal("Cooper Koch");
    expect(actors[i++]).to.equal("Daniel George");
    expect(actors[i++]).to.equal("Danny Bohnen");
    expect(actors[i++]).to.equal("Darwin del Fabro");
    expect(actors[i++]).to.equal("Destiny Danielle Freeman");
    expect(actors[i++]).to.equal("Devan Summers");
    expect(actors[i++]).to.equal("Drea de Matteo");
    expect(actors[i++]).to.equal("Eli Powers");
    expect(actors[i++]).to.equal("Embeth Davidtz");
    expect(actors[i++]).to.equal("Hayley Griffith");
    expect(actors[i++]).to.equal("Heaven Lupita Stamps");
    expect(actors[i++]).to.equal("Jack Caron");
    expect(actors[i++]).to.equal("Jack Hueter");
    expect(actors[i++]).to.equal("Janelle Beaudry");
    expect(actors[i++]).to.equal("Jaylen Hobdy");
    expect(actors[i++]).to.equal("Jerry O'Brien");
    expect(actors[i++]).to.equal("Jim Boyd");
    expect(actors[i++]).to.equal("Jim Ortlieb");
    expect(actors[i++]).to.equal("Joshua C Jackson");
    expect(actors[i++]).to.equal("Juan De Jesus");
    expect(actors[i++]).to.equal("K.D. O'Hair");
    expect(actors[i++]).to.equal("Kari Lee Cartwright");
    expect(actors[i++]).to.equal("Karin Justman");
    expect(actors[i++]).to.equal("Kyle Allen");
    expect(actors[i++]).to.equal("Leah Procito");
    expect(actors[i++]).to.equal("Liam Anderson");
    expect(actors[i++]).to.equal("Lowri Ann Richards");
    expect(actors[i++]).to.equal("Luis Da Silva Jr.");
    expect(actors[i++]).to.equal("Madeline Brewer");
    expect(actors[i++]).to.equal("Marisa Tomei");
    expect(actors[i++]).to.equal("Mark Ashworth");
    expect(actors[i++]).to.equal("Mark Wahlberg");
    expect(actors[i++]).to.equal("Mary Ann Schaub");
    expect(actors[i++]).to.equal("Matt Walsh");
    expect(actors[i++]).to.equal("Meagan Holder");
    expect(actors[i++]).to.equal("Michelle Monaghan");
    expect(actors[i++]).to.equal("Monique Kim");
    expect(actors[i++]).to.equal("Noelle Cameron");
    expect(actors[i++]).to.equal("Pamela Jayne Morgan");
    expect(actors[i++]).to.equal("Peter McSwiggin");
    expect(actors[i++]).to.equal("Philip Vaile-Lucason");
    expect(actors[i++]).to.equal("Quei Tann");
    expect(actors[i++]).to.equal("Rhys Coiro");
    expect(actors[i++]).to.equal("Rocco Presciutti");
    expect(actors[i++]).to.equal("Scotty Bohnen");
    expect(actors[i++]).to.equal("Sean Leser");
    expect(actors[i++]).to.equal("Simon Helberg");
    expect(actors[i++]).to.equal("Sofia Riba");
    expect(actors[i++]).to.equal("Sofía Palmero");
    expect(actors[i++]).to.equal("Steven Anthony Washington");
    expect(actors[i++]).to.equal("Storm Reid");
    expect(actors[i++]).to.equal("Theo Germaine");
    expect(actors[i++]).to.equal("Thomas Francis Murphy");
    expect(actors[i++]).to.equal("Tony Estrella");
    expect(actors[i++]).to.equal("Travis Fimmel");
  });

  it("handles depth 2", async () => {
    await load(2, 258);

    const response = await listActors({});
    const actors = response.actors;
    expect(actors).length(258);
    let i = 0;
    expect(actors[i++]).to.equal("AJ Zoldy");
    expect(actors[i++]).to.equal("Aaron Pierre");
    expect(actors[i++]).to.equal("Abbey Lee");
    expect(actors[i++]).to.equal("Adaline Swanson");
    expect(actors[i++]).to.equal("Adam Moryto");
    expect(actors[i++]).to.equal("Ahmad Dugas");
    expect(actors[i++]).to.equal("Aidan Bristow");
    expect(actors[i++]).to.equal("Aisha Dee");
    expect(actors[i++]).to.equal("Alana Jackson");
    expect(actors[i++]).to.equal("Alejandra Useche");
    expect(actors[i++]).to.equal("Alessandra Rosenfeld");
    expect(actors[i++]).to.equal("Alex Barber");
    expect(actors[i++]).to.equal("Alex Farquhar");
    expect(actors[i++]).to.equal("Alex Wolff");
    expect(actors[i++]).to.equal("Alexa Swinton");
    expect(actors[i++]).to.equal("Alexandra Shipp");
    expect(actors[i++]).to.equal("Alyana Hill");
    expect(actors[i++]).to.equal("Amanda Seyfried");
    expect(actors[i++]).to.equal("Americo Presciutti");
    expect(actors[i++]).to.equal("Amy Bernstein");
    expect(actors[i++]).to.equal("Amy Landecker");
    expect(actors[i++]).to.equal("Andrea Savage");
    expect(actors[i++]).to.equal("Andrew Polk");
    expect(actors[i++]).to.equal("Andrew Schulz");
    expect(actors[i++]).to.equal("Angel Murphy");
    expect(actors[i++]).to.equal("Anna Chlumsky");
    expect(actors[i++]).to.equal("Anna Lore");
    expect(actors[i++]).to.equal("Anthony Anderson");
    expect(actors[i++]).to.equal("Arden Myrin");
    expect(actors[i++]).to.equal("Arturo A. Baez");
    expect(actors[i++]).to.equal("Austin Crute");
    expect(actors[i++]).to.equal("Ava Zaria Lee");
    expect(actors[i++]).to.equal("Avery Tiiu Essex");
    expect(actors[i++]).to.equal("Becky Bass");
    expect(actors[i++]).to.equal("Billie Jordan");
    expect(actors[i++]).to.equal("Billy MacLellan");
    expect(actors[i++]).to.equal("Bobby Brown");
    expect(actors[i++]).to.equal("Boone Platt");
    expect(actors[i++]).to.equal("Briana McLean");
    expect(actors[i++]).to.equal("Brooke Jaye Taylor");
    expect(actors[i++]).to.equal("Bryan Greenberg");
    expect(actors[i++]).to.equal("Caleb Ward");
    expect(actors[i++]).to.equal("Carrie Preston");
    expect(actors[i++]).to.equal("Casie Baker");
    expect(actors[i++]).to.equal("Chayim Frenkel");
    expect(actors[i++]).to.equal("Chinyere Dobson");
    expect(actors[i++]).to.equal("Chris Jackson");
    expect(actors[i++]).to.equal("Christopher R Swanson");
    expect(actors[i++]).to.equal("Colin Blumenau");
    expect(actors[i++]).to.equal("Colson Baker");
    expect(actors[i++]).to.equal("Cooper Koch");
    expect(actors[i++]).to.equal("DJ Drama");
    expect(actors[i++]).to.equal("Dalila Ali Rajah");
    expect(actors[i++]).to.equal("Daniel George");
    expect(actors[i++]).to.equal("Daniel Henney");
    expect(actors[i++]).to.equal("Daniel Ison");
    expect(actors[i++]).to.equal("Danielle Nottingham");
    expect(actors[i++]).to.equal("Danny Bohnen");
    expect(actors[i++]).to.equal("Darren W. Marynuk");
    expect(actors[i++]).to.equal("Darwin del Fabro");
    expect(actors[i++]).to.equal("David Cade");
    expect(actors[i++]).to.equal("David Duchovny");
    expect(actors[i++]).to.equal("David James Elliott");
    expect(actors[i++]).to.equal("Deidra Ciolko");
    expect(actors[i++]).to.equal("Deon Cole");
    expect(actors[i++]).to.equal("Derya Derman");
    expect(actors[i++]).to.equal("Destiny Danielle Freeman");
    expect(actors[i++]).to.equal("Devan Summers");
    expect(actors[i++]).to.equal("Diva Zappa");
    expect(actors[i++]).to.equal("Doris Hancox");
    expect(actors[i++]).to.equal("Doug Hall");
    expect(actors[i++]).to.equal("Drea de Matteo");
    expect(actors[i++]).to.equal("Drew Brandon Jones");
    expect(actors[i++]).to.equal("Dylan Flashner");
    expect(actors[i++]).to.equal("Eddie Murphy");
    expect(actors[i++]).to.equal("Eli Powers");
    expect(actors[i++]).to.equal("Eliza Scanlen");
    expect(actors[i++]).to.equal("Elliott Gould");
    expect(actors[i++]).to.equal("Embeth Davidtz");
    expect(actors[i++]).to.equal("Emily Arlook");
    expect(actors[i++]).to.equal("Emily G. Miller");
    expect(actors[i++]).to.equal("Emun Elliott");
    expect(actors[i++]).to.equal("Eric Hoff");
    expect(actors[i++]).to.equal("Esteban Dager");
    expect(actors[i++]).to.equal("Felipe Esparza");
    expect(actors[i++]).to.equal("Fox Kent");
    expect(actors[i++]).to.equal("Francesca Eastwood");
    expect(actors[i++]).to.equal("Gael García Bernal");
    expect(actors[i++]).to.equal("Gavin Powers");
    expect(actors[i++]).to.equal("Genelle Williams");
    expect(actors[i++]).to.equal("Graham Abbey");
    expect(actors[i++]).to.equal("Gustaf Hammarsten");
    expect(actors[i++]).to.equal("Hal Linden");
    expect(actors[i++]).to.equal("Hamza Haq");
    expect(actors[i++]).to.equal("Hanxi Li");
    expect(actors[i++]).to.equal("Harley");
    expect(actors[i++]).to.equal("Hayley Griffith");
    expect(actors[i++]).to.equal("Heaven Lupita Stamps");
    expect(actors[i++]).to.equal("Helen Kozlowski");
    expect(actors[i++]).to.equal("Ian Sargent Phillips");
    expect(actors[i++]).to.equal("Jack Caron");
    expect(actors[i++]).to.equal("Jack Hueter");
    expect(actors[i++]).to.equal("Jameel Shivji");
    expect(actors[i++]).to.equal("Janelle Beaudry");
    expect(actors[i++]).to.equal("Jasmin Savoy Brown");
    expect(actors[i++]).to.equal("Javier Grajeda");
    expect(actors[i++]).to.equal("Jaylen Hobdy");
    expect(actors[i++]).to.equal("Jeffrey David Anderson");
    expect(actors[i++]).to.equal("Jeffrey Holsman");
    expect(actors[i++]).to.equal("Jennifer Garner");
    expect(actors[i++]).to.equal("Jerry O'Brien");
    expect(actors[i++]).to.equal("Jill Smith");
    expect(actors[i++]).to.equal("Jim Boyd");
    expect(actors[i++]).to.equal("Jim Gaffigan");
    expect(actors[i++]).to.equal("Jim McCaskill");
    expect(actors[i++]).to.equal("Jim Ortlieb");
    expect(actors[i++]).to.equal("Joaquim de Almeida");
    expect(actors[i++]).to.equal("Joe Powers");
    expect(actors[i++]).to.equal("Joel Nevells");
    expect(actors[i++]).to.equal("John Bishop");
    expect(actors[i++]).to.equal("John Twohy");
    expect(actors[i++]).to.equal("Jonah Hill");
    expect(actors[i++]).to.equal("Jordan Firstman");
    expect(actors[i++]).to.equal("Joshua C Jackson");
    expect(actors[i++]).to.equal("Juan Carlos Goméz Ortega");
    expect(actors[i++]).to.equal("Juan De Jesus");
    expect(actors[i++]).to.equal("Julia Louis-Dreyfus");
    expect(actors[i++]).to.equal("K.D. O'Hair");
    expect(actors[i++]).to.equal("Kailen Jude");
    expect(actors[i++]).to.equal("Karen Gillan");
    expect(actors[i++]).to.equal("Kari Lee Cartwright");
    expect(actors[i++]).to.equal("Karin Justman");
    expect(actors[i++]).to.equal("Karina Noelle Castillo");
    expect(actors[i++]).to.equal("Karson Mackie");
    expect(actors[i++]).to.equal("Kash Abdulmalik");
    expect(actors[i++]).to.equal("Kat Graham");
    expect(actors[i++]).to.equal("Kate Hennig");
    expect(actors[i++]).to.equal("Kate Moyer");
    expect(actors[i++]).to.equal("Kathleen Chalfant");
    expect(actors[i++]).to.equal("Katie Parker");
    expect(actors[i++]).to.equal("Kelly Martin");
    expect(actors[i++]).to.equal("Kelly Stables");
    expect(actors[i++]).to.equal("Ken Leung");
    expect(actors[i++]).to.equal("Kenya Barris");
    expect(actors[i++]).to.equal("Khadijah Haqq");
    expect(actors[i++]).to.equal("Kimberly Cheng");
    expect(actors[i++]).to.equal("Kyla-Drew");
    expect(actors[i++]).to.equal("Kyle Allen");
    expect(actors[i++]).to.equal("Kylie Begley");
    expect(actors[i++]).to.equal("Kym Whitley");
    expect(actors[i++]).to.equal("La La Anthony");
    expect(actors[i++]).to.equal("Laura Dromerick");
    expect(actors[i++]).to.equal("Lauren B. Mosley");
    expect(actors[i++]).to.equal("Lauren London");
    expect(actors[i++]).to.equal("Leah Procito");
    expect(actors[i++]).to.equal("Liam Anderson");
    expect(actors[i++]).to.equal("Liam Culhane");
    expect(actors[i++]).to.equal("Lincoln Brown");
    expect(actors[i++]).to.equal("Lisa K. Wyatt");
    expect(actors[i++]).to.equal("Lisa Yamada");
    expect(actors[i++]).to.equal("Louise Walter");
    expect(actors[i++]).to.equal("Lowri Ann Richards");
    expect(actors[i++]).to.equal("Luca Faustino Rodriguez");
    expect(actors[i++]).to.equal("Luis Da Silva Jr.");
    expect(actors[i++]).to.equal("M. Night Shyamalan");
    expect(actors[i++]).to.equal("Madeline Brewer");
    expect(actors[i++]).to.equal("Malik S");
    expect(actors[i++]).to.equal("Marcelo Tubert");
    expect(actors[i++]).to.equal("Marcus Mullins");
    expect(actors[i++]).to.equal("Margaux Da Silva");
    expect(actors[i++]).to.equal("Marisa Tomei");
    expect(actors[i++]).to.equal("Mark Ashworth");
    expect(actors[i++]).to.equal("Mark Fisher");
    expect(actors[i++]).to.equal("Mark Wahlberg");
    expect(actors[i++]).to.equal("Marla Garlin");
    expect(actors[i++]).to.equal("Mary Ann Schaub");
    expect(actors[i++]).to.equal("Matt Walsh");
    expect(actors[i++]).to.equal("Matthew Shear");
    expect(actors[i++]).to.equal("Mauricio Mendoza");
    expect(actors[i++]).to.equal("Meagan Holder");
    expect(actors[i++]).to.equal("Megan Suri");
    expect(actors[i++]).to.equal("Michael May");
    expect(actors[i++]).to.equal("Michael Segovia");
    expect(actors[i++]).to.equal("Michelle Giroux");
    expect(actors[i++]).to.equal("Michelle Monaghan");
    expect(actors[i++]).to.equal("Mikaya Fisher");
    expect(actors[i++]).to.equal("Mike Epps");
    expect(actors[i++]).to.equal("Molly Gordon");
    expect(actors[i++]).to.equal("Monica Bhatnagar");
    expect(actors[i++]).to.equal("Monique Kim");
    expect(actors[i++]).to.equal("Murray Gray");
    expect(actors[i++]).to.equal("Nelson Franklin");
    expect(actors[i++]).to.equal("Nerea Duhart");
    expect(actors[i++]).to.equal("Nia Long");
    expect(actors[i++]).to.equal("Nico Evers-Swindell");
    expect(actors[i++]).to.equal("Nikki Amuka-Bird");
    expect(actors[i++]).to.equal("Noelle Cameron");
    expect(actors[i++]).to.equal("Nolan River");
    expect(actors[i++]).to.equal("Oscar Camacho");
    expect(actors[i++]).to.equal("Pamela Jayne Morgan");
    expect(actors[i++]).to.equal("Paul Ben-Victor");
    expect(actors[i++]).to.equal("Paul Walter Hauser");
    expect(actors[i++]).to.equal("Peter McSwiggin");
    expect(actors[i++]).to.equal("Phil Popp");
    expect(actors[i++]).to.equal("Philip Vaile-Lucason");
    expect(actors[i++]).to.equal("Phoenix Ellis");
    expect(actors[i++]).to.equal("Pino Martinez");
    expect(actors[i++]).to.equal("Quei Tann");
    expect(actors[i++]).to.equal("Rahul Kohli");
    expect(actors[i++]).to.equal("Reese Levine");
    expect(actors[i++]).to.equal("Rhea Perlman");
    expect(actors[i++]).to.equal("Rhys Coiro");
    expect(actors[i++]).to.equal("Richard Benjamin");
    expect(actors[i++]).to.equal("Rick Chambers");
    expect(actors[i++]).to.equal("Rob Huebel");
    expect(actors[i++]).to.equal("Robert Diago DoQui");
    expect(actors[i++]).to.equal("Rocco Presciutti");
    expect(actors[i++]).to.equal("Romy Reiner");
    expect(actors[i++]).to.equal("Rose McIver");
    expect(actors[i++]).to.equal("Roy Abramsohn");
    expect(actors[i++]).to.equal("Rufus Sewell");
    expect(actors[i++]).to.equal("Ryan Patrick McGuffey");
    expect(actors[i++]).to.equal("Ryan Phillippe");
    expect(actors[i++]).to.equal("Sally Levi");
    expect(actors[i++]).to.equal("Sam Jay");
    expect(actors[i++]).to.equal("Scott Menville");
    expect(actors[i++]).to.equal("Scotty Bohnen");
    expect(actors[i++]).to.equal("Sean Leser");
    expect(actors[i++]).to.equal("Sean O'Bryan");
    expect(actors[i++]).to.equal("Sharar Ali-Speakes");
    expect(actors[i++]).to.equal("Simon Helberg");
    expect(actors[i++]).to.equal("Sloane Weber");
    expect(actors[i++]).to.equal("Sofia Riba");
    expect(actors[i++]).to.equal("Sofía Palmero");
    expect(actors[i++]).to.equal("Stephan James");
    expect(actors[i++]).to.equal("Steven Anthony Washington");
    expect(actors[i++]).to.equal("Storm Reid");
    expect(actors[i++]).to.equal("Tessa Hersh");
    expect(actors[i++]).to.equal("Theo Germaine");
    expect(actors[i++]).to.equal("Thomas Barbusca");
    expect(actors[i++]).to.equal("Thomas Francis Murphy");
    expect(actors[i++]).to.equal("Thomasin McKenzie");
    expect(actors[i++]).to.equal("Tim Griffin");
    expect(actors[i++]).to.equal("Todd Shotz");
    expect(actors[i++]).to.equal("Tongayi Chirisa");
    expect(actors[i++]).to.equal("Tony Estrella");
    expect(actors[i++]).to.equal("Tony Marra");
    expect(actors[i++]).to.equal("Tracy Vilar");
    expect(actors[i++]).to.equal("Travis Bennett");
    expect(actors[i++]).to.equal("Travis Fimmel");
    expect(actors[i++]).to.equal("Ty Molbak");
    expect(actors[i++]).to.equal("Vicky Krieps");
    expect(actors[i++]).to.equal("Viviana Salinas");
    expect(actors[i++]).to.equal("Winnie Holzman");
    expect(actors[i++]).to.equal("Wolfie Trausch");
    expect(actors[i++]).to.equal("Yan Joseph");
    expect(actors[i++]).to.equal("Yung Miami");
    expect(actors[i++]).to.equal("Zeke Alton");
  });

  it("handles depth 3", async () => {
    await loadHistory({depth: 3});

    const response = await listActors({});
    const actors = response.actors;
    expect(actors).length(312);
    let i = 0;
    expect(actors[i++]).to.equal("A. Russell Andrews");
    expect(actors[i++]).to.equal("AJ Zoldy");
    expect(actors[i++]).to.equal("Aaron Pierre");
    expect(actors[i++]).to.equal("Abbey Lee");
    expect(actors[i++]).to.equal("Adaline Swanson");
    expect(actors[i++]).to.equal("Adam Moryto");
    expect(actors[i++]).to.equal("Ahmad Dugas");
    expect(actors[i++]).to.equal("Aidan Bristow");
    expect(actors[i++]).to.equal("Aisha Dee");
    expect(actors[i++]).to.equal("Alana Jackson");
    expect(actors[i++]).to.equal("Alejandra Useche");
    expect(actors[i++]).to.equal("Alessandra Rosenfeld");
    expect(actors[i++]).to.equal("Alex Barber");
    expect(actors[i++]).to.equal("Alex Farquhar");
    expect(actors[i++]).to.equal("Alex Wolff");
    expect(actors[i++]).to.equal("Alexa Swinton");
    expect(actors[i++]).to.equal("Alexandra Shipp");
    expect(actors[i++]).to.equal("Alyana Hill");
    expect(actors[i++]).to.equal("Amanda Seyfried");
    expect(actors[i++]).to.equal("Americo Presciutti");
    expect(actors[i++]).to.equal("Amy Bernstein");
    expect(actors[i++]).to.equal("Amy Landecker");
    expect(actors[i++]).to.equal("Andrea Savage");
    expect(actors[i++]).to.equal("Andrew Polk");
    expect(actors[i++]).to.equal("Andrew Schulz");
    expect(actors[i++]).to.equal("Angel Murphy");
    expect(actors[i++]).to.equal("Anna Chlumsky");
    expect(actors[i++]).to.equal("Anna Lore");
    expect(actors[i++]).to.equal("Annie Ilonzeh");
    expect(actors[i++]).to.equal("Anthony Anderson");
    expect(actors[i++]).to.equal("Arden Myrin");
    expect(actors[i++]).to.equal("Arnold Chon");
    expect(actors[i++]).to.equal("Arturo A. Baez");
    expect(actors[i++]).to.equal("Austin Crute");
    expect(actors[i++]).to.equal("Austin Hébert");
    expect(actors[i++]).to.equal("Ava Zaria Lee");
    expect(actors[i++]).to.equal("Avery Tiiu Essex");
    expect(actors[i++]).to.equal("Becky Bass");
    expect(actors[i++]).to.equal("Billie Jordan");
    expect(actors[i++]).to.equal("Billy MacLellan");
    expect(actors[i++]).to.equal("Bobby Brown");
    expect(actors[i++]).to.equal("Boone Platt");
    expect(actors[i++]).to.equal("Briana McLean");
    expect(actors[i++]).to.equal("Brooke Jaye Taylor");
    expect(actors[i++]).to.equal("Bryan Greenberg");
    expect(actors[i++]).to.equal("C.C. Taylor");
    expect(actors[i++]).to.equal("Cailey Fleming");
    expect(actors[i++]).to.equal("Caleb Ward");
    expect(actors[i++]).to.equal("Carrie Preston");
    expect(actors[i++]).to.equal("Casie Baker");
    expect(actors[i++]).to.equal("Caspar Brun");
    expect(actors[i++]).to.equal("Charles Porter");
    expect(actors[i++]).to.equal("Chayim Frenkel");
    expect(actors[i++]).to.equal("Chinyere Dobson");
    expect(actors[i++]).to.equal("Chris Jackson");
    expect(actors[i++]).to.equal("Chris Johnson");
    expect(actors[i++]).to.equal("Christopher M. Campos");
    expect(actors[i++]).to.equal("Christopher R Swanson");
    expect(actors[i++]).to.equal("Colin Blumenau");
    expect(actors[i++]).to.equal("Colson Baker");
    expect(actors[i++]).to.equal("Cooper Koch");
    expect(actors[i++]).to.equal("DJ Drama");
    expect(actors[i++]).to.equal("Dalila Ali Rajah");
    expect(actors[i++]).to.equal("Daniel George");
    expect(actors[i++]).to.equal("Daniel Henney");
    expect(actors[i++]).to.equal("Daniel Ison");
    expect(actors[i++]).to.equal("Danielle Nottingham");
    expect(actors[i++]).to.equal("Danny Bohnen");
    expect(actors[i++]).to.equal("Darren W. Marynuk");
    expect(actors[i++]).to.equal("Darwin del Fabro");
    expect(actors[i++]).to.equal("David Cade");
    expect(actors[i++]).to.equal("David Duchovny");
    expect(actors[i++]).to.equal("David James Elliott");
    expect(actors[i++]).to.equal("Deidra Ciolko");
    expect(actors[i++]).to.equal("Denney Pierce");
    expect(actors[i++]).to.equal("Deon Cole");
    expect(actors[i++]).to.equal("Derya Derman");
    expect(actors[i++]).to.equal("Destiny Danielle Freeman");
    expect(actors[i++]).to.equal("Devan Summers");
    expect(actors[i++]).to.equal("Diva Zappa");
    expect(actors[i++]).to.equal("Donnie Smith");
    expect(actors[i++]).to.equal("Doris Hancox");
    expect(actors[i++]).to.equal("Doug Hall");
    expect(actors[i++]).to.equal("Drea de Matteo");
    expect(actors[i++]).to.equal("Drew Brandon Jones");
    expect(actors[i++]).to.equal("Dylan Flashner");
    expect(actors[i++]).to.equal("Eddie Murphy");
    expect(actors[i++]).to.equal("Eddie Shin");
    expect(actors[i++]).to.equal("Edilsy Vargas");
    expect(actors[i++]).to.equal("Edwin Garcia II");
    expect(actors[i++]).to.equal("Eli Powers");
    expect(actors[i++]).to.equal("Eliza Scanlen");
    expect(actors[i++]).to.equal("Elliott Gould");
    expect(actors[i++]).to.equal("Embeth Davidtz");
    expect(actors[i++]).to.equal("Emily Arlook");
    expect(actors[i++]).to.equal("Emily G. Miller");
    expect(actors[i++]).to.equal("Emma Thoraval");
    expect(actors[i++]).to.equal("Emun Elliott");
    expect(actors[i++]).to.equal("Eric Hoff");
    expect(actors[i++]).to.equal("Erin Carufel");
    expect(actors[i++]).to.equal("Esteban Dager");
    expect(actors[i++]).to.equal("Felipe Esparza");
    expect(actors[i++]).to.equal("Fox Kent");
    expect(actors[i++]).to.equal("Francesca Eastwood");
    expect(actors[i++]).to.equal("Gael García Bernal");
    expect(actors[i++]).to.equal("Gavin Powers");
    expect(actors[i++]).to.equal("Genelle Williams");
    expect(actors[i++]).to.equal("George Crayton");
    expect(actors[i++]).to.equal("Graham Abbey");
    expect(actors[i++]).to.equal("Gustaf Hammarsten");
    expect(actors[i++]).to.equal("Gustavo Escobar");
    expect(actors[i++]).to.equal("Hal Linden");
    expect(actors[i++]).to.equal("Hamza Haq");
    expect(actors[i++]).to.equal("Hanxi Li");
    expect(actors[i++]).to.equal("Harley");
    expect(actors[i++]).to.equal("Hayley Griffith");
    expect(actors[i++]).to.equal("Heaven Lupita Stamps");
    expect(actors[i++]).to.equal("Helen Kozlowski");
    expect(actors[i++]).to.equal("Hunter Wright");
    expect(actors[i++]).to.equal("Ian Casselberry");
    expect(actors[i++]).to.equal("Ian Sargent Phillips");
    expect(actors[i++]).to.equal("Jack Caron");
    expect(actors[i++]).to.equal("Jack Hueter");
    expect(actors[i++]).to.equal("Jameel Shivji");
    expect(actors[i++]).to.equal("Janelle Beaudry");
    expect(actors[i++]).to.equal("Jasmin Savoy Brown");
    expect(actors[i++]).to.equal("Javier Grajeda");
    expect(actors[i++]).to.equal("Jaylen Hobdy");
    expect(actors[i++]).to.equal("Jeff Harlan");
    expect(actors[i++]).to.equal("Jeff Hephner");
    expect(actors[i++]).to.equal("Jeffrey David Anderson");
    expect(actors[i++]).to.equal("Jeffrey Holsman");
    expect(actors[i++]).to.equal("Jennifer Garner");
    expect(actors[i++]).to.equal("Jerry O'Brien");
    expect(actors[i++]).to.equal("Jesus Trujillo");
    expect(actors[i++]).to.equal("Jill Smith");
    expect(actors[i++]).to.equal("Jim Boyd");
    expect(actors[i++]).to.equal("Jim Gaffigan");
    expect(actors[i++]).to.equal("Jim McCaskill");
    expect(actors[i++]).to.equal("Jim Ortlieb");
    expect(actors[i++]).to.equal("Joaquim de Almeida");
    expect(actors[i++]).to.equal("Joe Powers");
    expect(actors[i++]).to.equal("Joel Nevells");
    expect(actors[i++]).to.equal("John Bishop");
    expect(actors[i++]).to.equal("John Boyd");
    expect(actors[i++]).to.equal("John Gallagher Jr.");
    expect(actors[i++]).to.equal("John Ortiz");
    expect(actors[i++]).to.equal("John Twohy");
    expect(actors[i++]).to.equal("Johnny Ortiz");
    expect(actors[i++]).to.equal("Jonah Hill");
    expect(actors[i++]).to.equal("Jordan Firstman");
    expect(actors[i++]).to.equal("Joshua C Jackson");
    expect(actors[i++]).to.equal("Josue Barron");
    expect(actors[i++]).to.equal("Joy Benedict");
    expect(actors[i++]).to.equal("Juan Carlos Goméz Ortega");
    expect(actors[i++]).to.equal("Juan De Jesus");
    expect(actors[i++]).to.equal("Juan Pablo Raba");
    expect(actors[i++]).to.equal("Julia Louis-Dreyfus");
    expect(actors[i++]).to.equal("K.D. O'Hair");
    expect(actors[i++]).to.equal("Kailen Jude");
    expect(actors[i++]).to.equal("Karen Gillan");
    expect(actors[i++]).to.equal("Kari Lee Cartwright");
    expect(actors[i++]).to.equal("Karin Justman");
    expect(actors[i++]).to.equal("Karina Noelle Castillo");
    expect(actors[i++]).to.equal("Karson Mackie");
    expect(actors[i++]).to.equal("Kash Abdulmalik");
    expect(actors[i++]).to.equal("Kat Graham");
    expect(actors[i++]).to.equal("Kate Hennig");
    expect(actors[i++]).to.equal("Kate Moyer");
    expect(actors[i++]).to.equal("Kathleen Chalfant");
    expect(actors[i++]).to.equal("Katie Parker");
    expect(actors[i++]).to.equal("Kelly Martin");
    expect(actors[i++]).to.equal("Kelly Stables");
    expect(actors[i++]).to.equal("Ken Leung");
    expect(actors[i++]).to.equal("Kenya Barris");
    expect(actors[i++]).to.equal("Khadijah Haqq");
    expect(actors[i++]).to.equal("Kimberly Cheng");
    expect(actors[i++]).to.equal("Kyla-Drew");
    expect(actors[i++]).to.equal("Kyle Allen");
    expect(actors[i++]).to.equal("Kylie Begley");
    expect(actors[i++]).to.equal("Kym Whitley");
    expect(actors[i++]).to.equal("La La Anthony");
    expect(actors[i++]).to.equal("LaSaundra Gibson");
    expect(actors[i++]).to.equal("Laura Diaz");
    expect(actors[i++]).to.equal("Laura Dromerick");
    expect(actors[i++]).to.equal("Lauren B. Mosley");
    expect(actors[i++]).to.equal("Lauren London");
    expect(actors[i++]).to.equal("Leah Procito");
    expect(actors[i++]).to.equal("Liam Anderson");
    expect(actors[i++]).to.equal("Liam Culhane");
    expect(actors[i++]).to.equal("Lincoln Brown");
    expect(actors[i++]).to.equal("Lisa K. Wyatt");
    expect(actors[i++]).to.equal("Lisa Yamada");
    expect(actors[i++]).to.equal("Louise Walter");
    expect(actors[i++]).to.equal("Lowri Ann Richards");
    expect(actors[i++]).to.equal("Luca Faustino Rodriguez");
    expect(actors[i++]).to.equal("Luis Da Silva Jr.");
    expect(actors[i++]).to.equal("M. Night Shyamalan");
    expect(actors[i++]).to.equal("Madeline Brewer");
    expect(actors[i++]).to.equal("Malik S");
    expect(actors[i++]).to.equal("Marcelo Tubert");
    expect(actors[i++]).to.equal("Marcus Mullins");
    expect(actors[i++]).to.equal("Margaux Da Silva");
    expect(actors[i++]).to.equal("Mario Cortez");
    expect(actors[i++]).to.equal("Marisa Tomei");
    expect(actors[i++]).to.equal("Mark Ashworth");
    expect(actors[i++]).to.equal("Mark Fisher");
    expect(actors[i++]).to.equal("Mark Wahlberg");
    expect(actors[i++]).to.equal("Markina Brown");
    expect(actors[i++]).to.equal("Marla Garlin");
    expect(actors[i++]).to.equal("Mary Ann Schaub");
    expect(actors[i++]).to.equal("Matt Walsh");
    expect(actors[i++]).to.equal("Matthew Shear");
    expect(actors[i++]).to.equal("Mauricio Mendoza");
    expect(actors[i++]).to.equal("Meagan Holder");
    expect(actors[i++]).to.equal("Megan Suri");
    expect(actors[i++]).to.equal("Mel Fair");
    expect(actors[i++]).to.equal("Method Man");
    expect(actors[i++]).to.equal("Michael Adler");
    expect(actors[i++]).to.equal("Michael May");
    expect(actors[i++]).to.equal("Michael Mosley");
    expect(actors[i++]).to.equal("Michael Reventar");
    expect(actors[i++]).to.equal("Michael Segovia");
    expect(actors[i++]).to.equal("Michelle Giroux");
    expect(actors[i++]).to.equal("Michelle Monaghan");
    expect(actors[i++]).to.equal("Mikaya Fisher");
    expect(actors[i++]).to.equal("Mike Epps");
    expect(actors[i++]).to.equal("Molly Gordon");
    expect(actors[i++]).to.equal("Monica Bhatnagar");
    expect(actors[i++]).to.equal("Monique Kim");
    expect(actors[i++]).to.equal("Morris Greco");
    expect(actors[i++]).to.equal("Murray Gray");
    expect(actors[i++]).to.equal("Nelson Franklin");
    expect(actors[i++]).to.equal("Nerea Duhart");
    expect(actors[i++]).to.equal("Nia Long");
    expect(actors[i++]).to.equal("Nico Evers-Swindell");
    expect(actors[i++]).to.equal("Nikki Amuka-Bird");
    expect(actors[i++]).to.equal("Nilla Elizabeth Watkins");
    expect(actors[i++]).to.equal("Noelle Cameron");
    expect(actors[i++]).to.equal("Nolan River");
    expect(actors[i++]).to.equal("Oscar Camacho");
    expect(actors[i++]).to.equal("Pamela Jayne Morgan");
    expect(actors[i++]).to.equal("Paul Ben-Victor");
    expect(actors[i++]).to.equal("Paul Walter Hauser");
    expect(actors[i++]).to.equal("Pell James");
    expect(actors[i++]).to.equal("Peter McSwiggin");
    expect(actors[i++]).to.equal("Phil Popp");
    expect(actors[i++]).to.equal("Philip Vaile-Lucason");
    expect(actors[i++]).to.equal("Phoenix Ellis");
    expect(actors[i++]).to.equal("Pino Martinez");
    expect(actors[i++]).to.equal("Quei Tann");
    expect(actors[i++]).to.equal("Rahul Kohli");
    expect(actors[i++]).to.equal("Randy Gonzalez");
    expect(actors[i++]).to.equal("Reese Levine");
    expect(actors[i++]).to.equal("Rhea Perlman");
    expect(actors[i++]).to.equal("Rhys Coiro");
    expect(actors[i++]).to.equal("Richard Benjamin");
    expect(actors[i++]).to.equal("Richard Cabral");
    expect(actors[i++]).to.equal("Rick Chambers");
    expect(actors[i++]).to.equal("Rob Huebel");
    expect(actors[i++]).to.equal("Robert Diago DoQui");
    expect(actors[i++]).to.equal("Rocco Presciutti");
    expect(actors[i++]).to.equal("Roland Feliciano");
    expect(actors[i++]).to.equal("Romy Reiner");
    expect(actors[i++]).to.equal("Rose McIver");
    expect(actors[i++]).to.equal("Roy Abramsohn");
    expect(actors[i++]).to.equal("Rufus Sewell");
    expect(actors[i++]).to.equal("Ryan Patrick McGuffey");
    expect(actors[i++]).to.equal("Ryan Phillippe");
    expect(actors[i++]).to.equal("Sally Levi");
    expect(actors[i++]).to.equal("Sam Jay");
    expect(actors[i++]).to.equal("Sam Upton");
    expect(actors[i++]).to.equal("Samantha Edelstein");
    expect(actors[i++]).to.equal("Scott Menville");
    expect(actors[i++]).to.equal("Scotty Bohnen");
    expect(actors[i++]).to.equal("Sean A. Rosales");
    expect(actors[i++]).to.equal("Sean Leser");
    expect(actors[i++]).to.equal("Sean O'Bryan");
    expect(actors[i++]).to.equal("Sharar Ali-Speakes");
    expect(actors[i++]).to.equal("Simon Helberg");
    expect(actors[i++]).to.equal("Sloane Weber");
    expect(actors[i++]).to.equal("Sofia Riba");
    expect(actors[i++]).to.equal("Sofía Palmero");
    expect(actors[i++]).to.equal("Stephan James");
    expect(actors[i++]).to.equal("Steven Anthony Washington");
    expect(actors[i++]).to.equal("Storm Reid");
    expect(actors[i++]).to.equal("Tate Birchmore");
    expect(actors[i++]).to.equal("Tessa Hersh");
    expect(actors[i++]).to.equal("Theo Germaine");
    expect(actors[i++]).to.equal("Thomas Barbusca");
    expect(actors[i++]).to.equal("Thomas Francis Murphy");
    expect(actors[i++]).to.equal("Thomasin McKenzie");
    expect(actors[i++]).to.equal("Tim Griffin");
    expect(actors[i++]).to.equal("Todd Shotz");
    expect(actors[i++]).to.equal("Tongayi Chirisa");
    expect(actors[i++]).to.equal("Tony Estrella");
    expect(actors[i++]).to.equal("Tony Marra");
    expect(actors[i++]).to.equal("Tracy Vilar");
    expect(actors[i++]).to.equal("Travis Bennett");
    expect(actors[i++]).to.equal("Travis Fimmel");
    expect(actors[i++]).to.equal("Ty Molbak");
    expect(actors[i++]).to.equal("Tyson Ritter");
    expect(actors[i++]).to.equal("Vicky Krieps");
    expect(actors[i++]).to.equal("Victor Winters");
    expect(actors[i++]).to.equal("Viviana Salinas");
    expect(actors[i++]).to.equal("William Leong");
    expect(actors[i++]).to.equal("Winnie Holzman");
    expect(actors[i++]).to.equal("Wolfie Trausch");
    expect(actors[i++]).to.equal("YaYa Gosselin");
    expect(actors[i++]).to.equal("Yan Joseph");
    expect(actors[i++]).to.equal("Yung Miami");
    expect(actors[i++]).to.equal("Zeke Alton");
  });
});

describe("degreesAway", () => {
  it("handles depth 1", async () => {
    await load(1, 78);
    await validateDegree0();
  });

  it("handles depth 2", async () => {
    await load(2, 258);

    await validateDegree0();
    await validateDegree1();
  });

  it("handles depth 3", async () => {
    await load(3, 312);

    await validateDegree0();
    await validateDegree1();

    let movies = await validateDegrees("Victor winters", 2);
    validateMovie(movies!, 0, "One Way", 2022, "Kevin Bacon", "Storm Reid");
    validateMovie(movies!, 1, "Missing", 2023, "Storm Reid", "Kimberly Cheng");
    validateMovie(movies!, 2, "Peppermint", 2018, "Kimberly Cheng", "Victor Winters");

    movies = await validateDegrees("Chris Johnson", 2);
    validateMovie(movies!, 0, "One Way", 2022, "Kevin Bacon", "Storm Reid");
    validateMovie(movies!, 1, "Missing", 2023, "Storm Reid", "Kimberly Cheng");
    validateMovie(movies!, 2, "Peppermint", 2018, "Kimberly Cheng", "Chris Johnson");

    movies = await validateDegrees("Ian Casselberry", 2);
    validateMovie(movies!, 0, "One Way", 2022, "Kevin Bacon", "Storm Reid");
    validateMovie(movies!, 1, "Missing", 2023, "Storm Reid", "Nia Long");
    validateMovie(movies!, 2, "Keanu", 2016, "Nia Long", "Ian Casselberry");
  });
});

async function load(depth: number, expected: number) {
  const response = await loadHistory({depth: depth});
  expect(response.actorCount).to.equal(expected);
}

async function validateDegree0() {
  let movies = await validateDegrees("Adaline Swanson", 0);
  validateMovie(movies!, 0, "Space Oddity", 2022, "Kevin Bacon", "Adaline Swanson");

  movies = await validateDegrees("Joshua C Jackson", 0);
  validateMovie(movies!, 0, "You Should Have Left", 2020, "Kevin Bacon", "Joshua C Jackson");

  movies = await validateDegrees("michelle monaghan", 0);
  validateMovie(movies!, 0, "Patriots Day", 2016, "Kevin Bacon", "Michelle Monaghan");

  movies = await validateDegrees("storm reid", 0);
  validateMovie(movies!, 0, "One Way", 2022, "Kevin Bacon", "Storm Reid");
}

async function validateDegree1() {
  let movies = await validateDegrees("chayim frenkel", 1);
  validateMovie(movies!, 0, "The Darkness", 2016, "Kevin Bacon", "Matt Walsh");
  validateMovie(movies!, 1, "You People", 2023, "Matt Walsh", "Chayim Frenkel");

  movies = await validateDegrees("Gustaf Hammarsten", 1);
  validateMovie(movies!, 0, "Patriots Day", 2016, "Kevin Bacon", "Alex Wolff");
  validateMovie(movies!, 1, "Old", 2021, "Alex Wolff", "Gustaf Hammarsten");


  movies = await validateDegrees("Michael Segovia", 1);
  validateMovie(movies!, 0, "One Way", 2022, "Kevin Bacon", "Storm Reid");
  validateMovie(movies!, 1, "Missing", 2023, "Storm Reid", "Michael Segovia");

  movies = await validateDegrees("Genelle Williams", 1);
  validateMovie(movies!, 0, "One Way", 2022, "Kevin Bacon", "Travis Fimmel");
  validateMovie(movies!, 1, "Delia's Gone", 2022, "Travis Fimmel", "Genelle Williams");
}

async function validateDegrees(actorName: string, expected: number) {
  const response = await degreesAway({name: actorName});
  expect(response.degrees).to.equal(expected);
  expect(response.movies?.length).to.equal(expected + 1);
  return response.movies;
}

function validateMovie(movies: LinkedMovie[], index: number, title: string, year: number | undefined, innerActor: string, outerActor: string) {
  const movie = movies[index];
  expect(movie).is.not.null;
  expect(movie.title).to.equal(title);
  expect(movie.year).to.equal(year);
  expect(movie.innerActor).to.equal(innerActor);
  expect(movie.outerActor).to.equal(outerActor);
}